### ISSUE TITLE
Do Not Disturb Mode

### ISSUE THREAD

**Issue by ghost** [dailydotdev/daily#103]
I am not sure whether to put this as a bug or a feature request. The 'Do Not Disturb' mode turns off the extension for the suggested period of time and replaces the new tab page with [Google](https://google.com). For users like me who prefer other search engines as their default like DuckDuckGo or StartPage, can you add a setting to set the default search engine for the 'Do Not Disturb' mode?

**Comment by idoshamun** [comment]
Hi @quostta,
Thanks for using Daily and sharing your ideas :)
I can relate with your suggestion and we will see how we can incorporate it as part of the DND feature.

**Comment by idoshamun** [comment]
We've just finished a product planning meeting and decided to prioritize this issue due to high demand.
The new change will include setting a custom redirect page for DND and a custom number of hours to turn it on for.
@KL13NT kindly volunteered to contribute this feature as part of Hacktoberfest.
In a few days, I'll upload the designs so we can proceed with the development.
Thanks everyone! ✌️

**Comment by idoshamun** [comment]
The design is ready 🥳
![Popup](https://user-images.githubusercontent.com/1993245/95309346-b4b66880-0893-11eb-9d88-a69d23b11817.jpg)
![Guidelines](https://user-images.githubusercontent.com/1993245/95309372-bb44e000-0893-11eb-9c25-dfed7005fb02.jpg)

As you can see in the new design instead of opening a context menu, a popup window is shown.
In the new window, the user can choose to set the URL and they can also set the time, including a custom duration.

When the DND is turned on, a context menu will be shown upon click with a single option to turn it off.

Implementation details:
The skeleton of the popup is very similar to the [new source popup](https://github.com/dailydotdev/daily-apps/blob/master/packages/extension/src/components/DaNewSource.vue) and can be copied from there.
We have already developed components for text input, radio buttons, and dropdowns which are everything you need to implement this feature. The text input and radio button are used in the link above in the new source popup, and the dropdown is used in the [integration popup](https://github.com/dailydotdev/daily-apps/blob/master/packages/extension/src/components/DaIntegrations.vue).

@KL13NT please send me a DM on [Twitter](https://twitter.com/idoshamun) and I'll give you access to our InVision project so you can inspect everything. I would love to guide you through everything and help you with whatever necessary.

**Comment by idoshamun** [comment]
Hey @KL13NT,

Could you please confirm that you're working on this issue?

**Comment by KL13NT** [comment]
Hey @idoshamun, was busy the past few days and couldn't get to work on this. When I'm ready to work on it I'll reply here (if no one else took it).

**Comment by idoshamun** [comment]
Ok, no worries. Let me know when you're available

**Comment by sshanzel** [comment]
I can work on this if it is still free for grabs! 😁

**Comment by idoshamun** [comment]
Hey @sshanzel,

Long time :)
We are now in a process of merging together the codebase of the webapp and the extension.
Once we finish this process it should be easier to contribute and we will be open to contributions again.

Thanks for the will to contribute. It's highly appreciated :)

**Comment by sshanzel** [comment]
Been a long time indeed!

Oh, I see. That sounds amazing! I shall wait for it to finish then. You can expect me in front of the line for sure!

**Comment by idoshamun** [comment]
Wow! I would love to see you on the front line.
Thanks for being awesome.

**Comment by idoshamun** [comment]
@sshanzel the merge was completed and we're ready to accept contributions once more.
If you still want to grab it let me know.

Here's the Sketch Cloud project with the design ready for implementation (we moved from inVision):
https://www.sketch.com/s/2549ccf9-b98c-413f-96fb-81b05b59e65f/a/PGW997P

We have also a new project for the extension and the webapp. You can find it here:
https://github.com/dailydotdev/apps

It's a monorepo, the extension project is here: https://github.com/dailydotdev/apps/tree/master/packages/extension

As always I'm here for anything, just let me know if you are up to it 🤩

**Comment by sshanzel** [comment]
@idoshamun sounds awesome that the merging was finished smoothly!

I shall work on this as soon as I get the chance to. I'll let you know if I would need anything! Thank you! 🍻
