### ISSUE TITLE
🐛 BUG: Unable to comment

### ISSUE THREAD

**Issue by frank-connolly** [dailydotdev/daily#1236]
### What went wrong? 🤔

I was catching up on welcoming newcomers to my squad and now I'm unable to comment on the post anymore.

### Expected Behavior

The comment to post successfully

### Steps to Reproduce Issue

```bash
1. Go to 'Just Java' squad - it is public
2. Click on the pinned welcome post
3. Scroll down through the million 'Welcome' comments I left as guided by dailydev notifications
4. See the error - I can no longer post comments. Not sure if you'll see that.
```

### Solution Proposed

Reveal any limit number on comments. Remove or bump this up for squad admins. 

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by frank-connolly** [comment]
Seems I am now able to comment and assume there is some hidden cooldown timer to prevent spamming?
Will close bug but would be nice to have it confirmed

**Comment by frank-connolly** [comment]
This is still an issue. 
Due to [Bug#1245](https://github.com/dailydotdev/daily/issues/1245) I have to wait to get to my desktop before I can catch up on welcome notifications, however I quickly hit the cooldown timer working through them. I'm managing two squads and it seems the cooldown is affected by me commenting to either. 
This is annoying as I have to manually remember where I got to in the notifications and work through them in batches.  

My unsolicited suggestion: A squad post comment should not count towards cooldown if the poster is an admin of that squad. The risk is minimal as admins should not be spamming their own squads.

**Comment by idoshamun** [comment]
We've been experiencing a lot of spam lately, so we had to do some quick and dirty hacks to prevent it.
I understand your issue and we'll think how best we can solve it

**Comment by Akkitto** [comment]
@idoshamun

The platform made an excellent first impression, when I started using it, so I went with the Plus membership right from the start.

This is a major road block and, to be honest, kinda ridiculous, as I paid 12 months in advance for the subscription and I barely commented anything. Even worse, it's not an hourly limit. It's a limit with a much higher impact. Haven't been able to post a single comment for hours, even though I am a Plus member with transparent profile, who anyone can check for whether I'm actually a real person or a bot.

The worst thing about this is, that I'm just trying out the service for now, by commenting here and there, to see how well this stuff works. I'm not even in a squad. If I were in a squad or really engage daily in some interesting topic, I would comment easily 30 times as much as I did today, within a fairly short timespan.

The service seems great in most aspects, but this issue here is a major showstopper & absolute No-Go.

**Comment by idoshamun** [comment]
Hi @Akkitto,

Thanks for trusting our service and purchasing the Plus plan. I take your feedback with all seriousness. And we're going to think how to overcome this. I'll keep you all posted

**Comment by idoshamun** [comment]
@Akkitto a fix is on the way! we already have a reputation threshold for ignoring the rate limit, I added plus as another criteria. Once it gets deployed I'll ping you again

**Comment by idoshamun** [comment]
The fix is live!

**Comment by Akkitto** [comment]
@idoshamun

> The fix is live!

Wow! You really put the pedal to the metal! 🙂

So far, since I got the issue, it did not re-appear again, even before the fix went live. Not sure why it went off in the first place.

I did not want to "test", whether it works by actually spamming, so I cannot confirm the fix. 😜 😁

Great to see this astonishing effort, thank you very much for that! 🥇
