### ISSUE TITLE
 🧩 FEATURE REQUEST: Bookmark icon on the article navigated through daily

### ISSUE THREAD

**Issue by parwatCodes** [dailydotdev/daily#126]
As of now, we can bookmark articles from the daily extension only.
It would be great if there will be a bookmark button in the articles/pages opened through daily.

## Use case:

A user will only bookmark if he feels the article is important and helps him further.

- User opens chrome, A new tab with daily extension full of articles(Card) is loaded.
- The user reads the title of the articles. The title looks interesting, lets read it, clicks the article(Card). Another tab opens for the article.
- Now to bookmark he had to navigate to the previous tab or open an empty tab. After he does that he'll look for that article, finds it, bookmarks it.

----------

### Suggestion

Instead of doing all these it will be much ease for a user if there is an icon to bookmark on the articles/pages opened through the daily extension. 

i.e: 
![DeepinScreenshot_select-area_20191127102547](https://user-images.githubusercontent.com/19905275/69694287-4e53ac00-1100-11ea-91a1-36da3b8e75e2.png)

**Comment by idoshamun** [comment]
Hi @p0k8h,

This is a very interesting idea! Let me discuss it internally.
Thank you for your suggestion :)

**Comment by idoshamun** [comment]
After discussing with @tsahimatsliah, we agreed that this is a valuable and desired feature. We will follow up with a design suggestion for this button.
In the meantime, if someone would like to contribute this feature it will be awesome :rocket:

**Comment by sshanzel** [comment]
Hi @idoshamun can you brief what approach we will be doing to get this started? I don't have much experience on extensions yet but i am more than willing to get this done! :D

**Comment by idoshamun** [comment]
Hi @sshanzel,
Thank you once more :heart: 
We have to create a [content-script](https://developer.chrome.com/extensions/content_scripts#programmatic) and to inject it programmatically.
Before injecting the bookmark button, we have to validate that the webpage is in the daily database with a simple http request (need to create this one as well).
In addition, any permission that is needed for this purpose (I think it's only `activeTab`) should be optional permission as we don't want to force the user with providing more personal data.
Once the button is clicked the webpage should be saved to daily bookmarks.
The button itself is not yet designed so once you confirm we should proceed with designing this button.
I can take care of the needed API to validate if a webpage exists if you want.
This issue is very tricky, bear in mind. I would be glad to assist along the way in everything.

**Comment by anthony-dallagnola** [comment]
Hello,
It seems to be an interesting feature to add. If sshanzel doesn't have time or don't want to do it anymore I would gladly give it a try. :)

**Comment by sshanzel** [comment]
That would be nice! I'm actually quite occupied with the Vim Navigation feat right now. So yeah do it bruh! 😁

**Comment by idoshamun** [comment]
Hi @anthony-dallagnola :)
Let's give it a go! We can start with a simple proof of concept and then decide how to proceed.
The first step is to check if it's possible to add this button but with optional permissions. Meaning every user will have to opt-in for this button rather than getting it by default.
I believe many users would not like to give this permission but still would love to use Daily.
For the first step, the design doesn't really matter just to see that it's feasible.
You can find me on our slack for direct messaging (http://slack.dailynow.co/)

**Comment by anthony-dallagnola** [comment]
Hello @idoshamun 
Ok I will check these out. I have never used permissions before so I need to read about that.
Then I will add a simple button to go with it.

**Comment by idoshamun** [comment]
Perfect! Let me know if you need any help

**Comment by rebelchris** [comment]
Closing this, as the companion solves this.
