### ISSUE TITLE
🐛 BUG: with the same account, cant login on mobile

### ISSUE THREAD

**Issue by enkr1** [dailydotdev/daily#1339]
### What went wrong? 🤔

this might sound dumb ... but i connected with all my social accounts and reset password, with the associated email. when i tried to login from mobile, it keeps showing me: 
![image](https://github.com/user-attachments/assets/762dc5a3-1931-4c1c-94bc-91d7e8b27750)

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by nensidosari** [comment]
Hi @enkr1, 

Thank you for reporting the issue.
The app you've actually downloaded is not our app, that's why you're not able to login. 

If you want to experience daily.dev in mobile, please follow the guide [here](https://docs.daily.dev/docs/getting-started/pwa) to get our app for either iOS or Android.
