### ISSUE TITLE
🐛 BUG: Sometimes articles do not have an arrow to jump to the artilce.

### ISSUE THREAD

**Issue by danieltoomey** [dailydotdev/daily#1355]
### What went wrong? 🤔

In this morning's list, one of the articles is "6 atomic habits of highly efficient CTOs".  When I hover I do not see an arrow for the link.  The other articles around that one do.  I can click on the article (without a visible arrow),

### Expected Behavior

I expected to see an arrow for any article I hover over.

### Steps to Reproduce Issue

```bash
1. Go to Daily Feed
2. Hover over each article in the feed
3. Notice whether an arrow icon is displayed or not
4. See the error
```

### Solution Proposed

I am not sure what makes an article not have a hover.  Maybe there is some context in the article presented that is overriding your code.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

mac, chrome

### Browsers

Chrome

### OS

Mac

### Version of daily.dev

Not sure how to see - I am using your website

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by danieltoomey** [comment]
It is a Read Post icon that I am looking for

**Comment by sabdailydev** [comment]
@danieltoomey Thanks for reporting.It would be great if you could share some sample links so that we can clarify. Not all posts would have a "Read post" button since some posts could be 

1. Collections (if there are too many posts about the same topic - we summarize the info to save time for the user)
2. Freeform posts that are user generated where the post contains the original content.
