### ISSUE TITLE
🐛 BUG: Shortcut link fields acting crazy..

### ISSUE THREAD

**Issue by Scarlywebs** [dailydotdev/daily#1466]
### What went wrong? 🤔

Hi, I'm unsure if this is a bug, but as I put in a link to save in my shortcuts the fields start to act all glitchy lol.
I uploaded a video here showing the form field twitching like crazy.  [Video Link](https://app.screencast.com/sdXq1uEEZp2JM)

I also uploaded it just in case the link does not work.
https://github.com/user-attachments/assets/8581d805-2d55-43ef-9368-0102cebc5624

### Steps to Reproduce Issue

```bash
1. Go to 'Shortcuts > manage'
2. Click on any of the shortcut fields
3. Start writing "https" stop mid-way through and hold you will see the error on the bottom glitching out.
4. in video shows as well even if I delete the text I just wrote on the field it will still get stuck because the error stays there.
```

### Environment

Chrome Browser

### Browsers

Chrome

### OS

Windows

### Version of daily.dev

Cannot find it, whatever that is out as of September 28, 2024

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment]
Hi @Scarlywebs,

Thanks for the report. We will look into it

**Comment by CR4ZED** [comment]
From the video, it looks like the input validation state is not handled correctly. I want to use breakpoints to find the main issue, but I can’t run the web app locally. Here’s the error message I see when I try to run the project. So far, I found that the local server is not working because the client-side is trying to connect to localhost:5000 instead of the Gitpod URL.

<img width="1680" alt="Screenshot 2024-09-30 at 8 21 37 PM" src="https://github.com/user-attachments/assets/7abd6f3c-b467-4982-a82a-4cb18177c31d">

**Comment by sshanzel** [comment]
@CR4ZED glad to let you know that the GitPod environment should now be back and running again 🥳

**Comment by satvik2131** [comment]
@sshanzel 
<img width="1280" alt="Screenshot 2024-10-16 at 3 52 15 PM" src="https://github.com/user-attachments/assets/26ffe5b5-b044-4489-8285-ec511d0f2f6b">
can't see the add shortcut option , is it removed

**Comment by sshanzel** [comment]
Hi @satvik2131, it is only available in the extension version. Also, I think @Abhi-Bohora has [raised a PR](https://github.com/dailydotdev/apps/pull/3697) already to fix it.

**Comment by sshanzel** [comment]
More details here: https://github.com/dailydotdev/daily/issues/1357#issuecomment-2446044400

To summarize, this should be fixed on our next extension updated 🚀 

Thank you for reporting 🙏
