### ISSUE TITLE
🐛 BUG: Unable to Submit Account Details

### ISSUE THREAD

**Issue by AlaguSelvan** [dailydotdev/daily#156]
### What went wrong? 🤔
Confirm Button Disabled after entering all details

### Expected Behavior
It should Submit be enabled after entering all details.

### Actual Behavior
Confirm Button is disabled after entering all details.

### Steps to Reproduce Issue
![daily-bug](https://user-images.githubusercontent.com/34230909/82783958-370e3500-9e7d-11ea-8cb5-f65f0a168b5e.gif)

### Solution
It should submit after entering all details, and should not ask if the user is logged.

### Environment
Windows 10 Pro
Chrome Version 83.0.4103.61 (Official Build) (64-bit)

#### Operating System
Windows 10 Pro

#### Version of Daily
Latest

#### Browser
Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by idoshamun** [comment]
Hi @AlaguSelvan,

Thanks for submitting this critical bug!
I will try to investigate the cause of this bug but in the meantime, you can enable the button using Chrome DevTools.
Run the following:
`$('button[type="submit"]').disabled = false;`
Make sure the information is set correctly, otherwise server may return status code 400.

Please let me know how it goes

**Comment by idoshamun** [comment]
I'm glad to share that I've found and fixed the bug. Hopefully I will release it as soon as I can.

**Comment by idoshamun** [comment]
This fix is available in v2.15.3 which is already published
