### ISSUE TITLE
🧩 FEATURE REQUEST: Show all available tags

### ISSUE THREAD

**Issue by NyWn** [dailydotdev/daily#166]
### Description

It'd be useful to see all of the tags that are available in addition to the "Hot Tags".

### Solution

I imagine it could be a simple "View all" button or link in the "View Tags List", possibly in between "My Tags" and "Hot Tags"

### Alternate Solutions

N/A

**Comment by idoshamun** [comment]
Hi @NyWn,

Thanks for your suggestion 🌟
Using the search functionality you can find other tags as well, we have hundreds of tags because it basically a free text by the author.
We try to rank them by the number of occurrences but I agree we need to provide better discovery for tags.

**Comment by idoshamun** [comment]
I have pushed a new version to our API to address this issue.
Although you will not have the possibility to see all the tags just because we have so many of them 😉
You will now be able to find more tags through the search functionality than before.
Feel free to check out the PR linked above for more details about the actual implementation.

**Comment by NyWn** [comment]
Awesome, thank you - definitely seeing a lot more tags now!
