### ISSUE TITLE
🐛 BUG: Created duplicated accounts (same e-mail)

### ISSUE THREAD

**Issue by fabio-s-franco** [dailydotdev/daily#211]
### What went wrong? 🤔

I somehow managed to create two accounts under the same e-mail. I think it happened when I wanted to enter the sticker referral context through my phone. Previously I had only logged in via the desktop browser, when I logged in via the phone I used google as sign in method because it was available.

So, I noticed there was something wrong as the referral url was different when I copied it from the phone instead of the desktop. So I went to double check and both e-mails matched, but not my full name profile (my desktop profile contains my middle name, my mobile profile doesn't).

Double checking now, I verified I logged in via github for with the desktop, so that google login created a second account, which means now I have two accounts and I think I will likely be getting duplicate emails.

So, we may not have a coding bug, but more of an UX bug. Since I didn't remember I actually used github before I endedup in this situation. Moreover, not sure my e-mail address had been verified before, but if it hadn't then your platform can be potentially used for spam and if it has, then it should've detected the conflicting account creation with the same email.

### Expected Behavior

I expected that if there is something unique about be that definitely would be my e-mail and that regardless if I use github or google to sign in, it should point towards the same account. Now I want to know if there is a way to joint the two. I also experience two things that could be improved:

1 - It's very annoying that I cannot navigate to anywhere from the promotional sticker page. I should be able to go to my profile page, or simply to my home from there. It made me waste time looking for something to click to get to my profile.
2 - The referral link should have an option to be randomized (like the one I actually got with the second account). This has to do with the ability of maintaining privacy. Maybe I don't want to share my username.

### Actual Behavior

It creates two different accounts if we try to sign in using both github and google.

### Steps to Reproduce Issue

Sign in using github (use a google email).
Sign in using google (the same e-mail used above).

### Solution

Use e-mail as a unique key and make sure you verify the e-mail address actually belongs to the owner. Github is not proof that I own my gmail e-mail and I am also able to set anything in the e-mail field.

If e-mail is an unique key, then make sure the user can use only one account by either warning him of having already an account with that e-mail or create a safe way to merge the sign-ins using both platforms. You could send a magic link to the e-mail if the sign-in is not done via google, as that would prove the ownership so you could safely link both log ins

### Environment

Not relevant.

#### Operating System

Not relevant

#### Version of Daily

Not relevant

#### Browser

Microsoft Edge (latest)

**Comment by idoshamun** [comment]
Hey @fabio-510,

Thanks for the detailed explanation.
Unfortunately, our authentication system doesn't support merging to account providers into one user at the moment.
If you want me to proceed with deleting one of your accounts please shoot us an email at hi@daily.dev and state which one of them you want to delete.

Regarding the referral link, there is no reason to hide your username as it's publicly available in the system. It is not private data so we show the username on your profile and in other places, just like in GitHub, Twitter, and other sites.

I'm closing this issue, for the time being, feel free to open it again if needed.

**Comment by fabio-510** [comment]
I think the least that needs to be addressed is an e-mail verification. I can put any e-mail there and there is no verification for ownership.

I would like to reiterate that the referral link should allow you not to show your username. If the username is publicly available in the system it's even worse, because username is considered personal information under GDPR regulations and needs consent to be shared. The consent needs to be clearly given (like in github). Not sure I am missing something, but I really didn't see it, so maybe you can help clarify or give a second thought to this.
In any case, even if we discard any GDPR regulation issues, you shouldn't simply assume that there are no reasons to hide my username. For example, if my username is related to my e-mail I don't want to broadcast something that may lead to my email when I am doing a referral. If I am sharing a concern, it's as a concern I have as a user. I acknowledge that you may want to prioritize other issues, but dismissing it is not really a good approach. Word of advice of a peer in the industry, listen to your users.

Finally, to the motive that lead for me to create this issue in the first place. I am here to help, because I believe on what you're doing and appreciate the effort on the service you're trying to provide or else I would not have been spending my time here, but I really think you should try minimizing things that drive users away. And the issue with duplicate accounts is one of them.

Again, maybe not a priority, but it should be tracked. If you close it, it will be lost and it won't be addressed. And it is an issue, even though you put it as a lack of support. It's not really about merging (when I mentioned it, it was about a way to deal with the conflict), but about ensuring the authentication mechanism is not confused with the authorization, which seems to be the case. Authentication should just be a way to identify me, not create me and it should point to a single user and not make two when it is about the same person which can be uniquely identified via e-mail.

I will try to reopen it so you see it again. Don't want to be pushy and it's really not my place, close it again if you think that's what you believe is best.

**Comment by fabio-510** [comment]
@idoshamun I don't think I have the power to reopen the issue. So it's up to you.

**Comment by idoshamun** [comment]
I'm sorry if I made you feel like I'm dismissing the issue when I certainly don't.
The fact that I closed the issue doesn't mean that I'm not aware or planning to deal with this. It's just that I know as I mentioned before that I can't fix this matter in the upcoming months and I don't want this issue to be stale. But I don't mind opening it again, so I'll do so.
I appreciate you dedicated the time to reach out and provide all this relevant information, this is not taken for granted.
Finally, we're a team of 3 and only 1 developer (me), we have to prioritize hard and focus on the important aspects of our product. I agree that the authentication system is confusing but it's definitely not the reason why users leave us. As you suggested, we listen carefully to all our users and prioritize accordingly.
Hopefully, you can understand the situation. 🙏

**Comment by fabio-510** [comment]
I can understand of course, that's why I mentioned maybe it's not a priority, but it didn't come across this way. So it's mainly about the way it was communicated by you.

Anyway, I don't want to sound like I know how you should track this issue, so I won't mind you closing it. If I get the chance I will try contributing to the issue.

Good luck.

**Comment by idoshamun** [comment]
I'm sorry if I didn't communicate it correctly 🙏

It's ok, I can leave that open. No worries.

I'm looking forward to seeing you around :)
