### ISSUE TITLE
🧩 FEATURE REQUEST: Show article tags in the feed

### ISSUE THREAD

**Issue by mshddev** [dailydotdev/daily#247]
### Description
i want to be able to see in which tag is this article belong to.

### Solution
display tag label in article list

**Comment by esau-morais** [comment]
Actually, this is already possible. Check the image below:

![tags](https://user-images.githubusercontent.com/55207584/105490661-dcd7a500-5c93-11eb-8519-21c63875b4db.png)

**Comment by mshddev** [comment]
Hi @esau-morais, I see. The tags below the time only appear in the comment section. What i suggest is in the article listing. Wouldn't be great if users can quickly spot which tag is this article belong to? Many news/article website did that. It does help. It just my opinion. Anyway, thanks for responding.

**Comment by idoshamun** [comment]
Hi @mshddev, we used to show the tags of the articles in the cards. Due to some design considerations, we decided to remove it from there. The tags can bloat the card size, and we don't think this information is necessary while scrolling in the feed. I hope that makes sense to you :)

@esau-morais thanks for the help!

**Comment by mshddev** [comment]
@idoshamun oke that's understandable. Thanks for the explanation.
