### ISSUE TITLE
🧩 FEATURE REQUEST: Connect multiple social accounts to a daily.dev account

### ISSUE THREAD

**Issue by jaloplo** [dailydotdev/daily#253]
### Description

I would like to associate different accounts from several sources (github, gmail, etc.) into a unique dailydotdev account.

### Solution

I would like to add the additional accounts from the profile menu. For example, adding a new tab on the right of "Reputation" menu. The options could be listing the current associated accounts and one button to add some more from different sources.

### Alternate Solutions

Another solution could be to transfer the reputation, articles and all profile information from one account to another.

In my case, I would like to do move my earnings, reputations and all the stuff from my personal github account to the professional one.

**Comment by idoshamun** [comment]
Hi!

This feature is definitely on our roadmap but we're focused on the web version at the moment so it's not going to be launched in the upcoming weeks.
Shoot us an email at hi@daily.dev so we can resolve your specific issue.
Anyway, I'll leave this issue open to remember we have to add support for multiple accounts.

**Comment by jaloplo** [comment]
@idoshamun thanks for your response. 

This is not an urgent issue from my side so I can wait for the feature to be released ;)

**Comment by idoshamun** [comment]
Thank you Jaime :)

**Comment by idoshamun** [comment]
We've just released our new authentication system. Please check out the release notes and try out the new features.
https://app.daily.dev/posts/IEnARQTZA
Looking forward to hear your feedback :)

**Comment by liar666** [comment]
The feature is nice, it allows to link any previously created account (e.g. non-social-media/email-created account) to a new social media.
Unfortunately, it cannot do the converse: I created an account based on Gmail, I'd like to link it to an non-social-media/email-created account, which is not offered.
I'd like to do this because I'll destroy the Gmail account soon, but I want to still be able to access my dailydev account.
I've try to do itthe reverse way: I created a non-social-media/email-created account and tried to link it with my Google account, but then I get an error saying the GMail account is already linked to another dailydev account.

**Comment by idoshamun** [comment]
@liar666 we already support the use case you present. To associate an existing account with an email-password, navigate to this page: https://app.daily.dev/account/security. Set a password, and that's it. Now you should be able to remove the association to google and use email and password to login. Let me know if it works.
