### ISSUE TITLE
🧩 FEATURE REQUEST:  Filter by read

### ISSUE THREAD

**Issue by ach5910** [dailydotdev/daily#283]
## Feature Request

Read articles should be optionally filtered out of my feed.

### Description

I would like to have the ability to update my default settings to filter out any article/blog post that I've already read from my feed. This would prevent me from scrolling through content that I've already read whenever returning to the app.

### Solution

Use the same logic used to conditionally render blog/article cards a different color based on it's visited/read state to instead conditionally remove the items from my feed.

This could be an optional setting that could be toggled on/off from the users profile or as a persisted filter setting from the list view.

### Alternate Solutions

It would also be nice to be able to  manually remove items that I haven't read but want removed from my feed so that I don't have to spend time scrolling past stale content when returning to the app. 

### General Feedback

I just started using this app a few weeks ago and I'm a big fan. Right now I'm using the Chrome browser extension on my laptop and the PWA installed on my mobile phone's home-screen. Both experiences are equally full-featured with impressively responsive UIs that are simple, clean and intuitive. 

I just want to thank the entire team for creating such a fantastic resource thats easy and enjoyable to use. I'll continue to share your app with my colleagues and peers alike.

Additionally, if this is an open source project and you're looking for community support I'd be interested in contributing to help resolve issues/bugs/tickets or explore experimental features.

**Comment by idoshamun** [comment]
Hey @ach5910,

Thanks for yet another great suggestion!
Do you
 know why it's great? Because it already exists! 🔥
Open the settings panel in the web app or the extension and hit the toggle button. You need a daily.dev account to enable this setting, and it will automatically be synced to all your devices.
<img width="1904" alt="Screen Shot 2021-05-20 at 16 52 58" src="https://user-images.githubusercontent.com/1993245/118990962-ff50a500-b98b-11eb-9b2b-36b4c926c28b.png">

I sent you an email 7 days ago with a surprise that you really need to check out. 🤪

As for your feedback, it means the whole world to us. It pumps us with motivation to deliver even more awesome features to you and others. It's so great that you spread the word and help us grow. Make sure you use your referral link so [you can win awesome prizes](https://daily.dev/monthly-prize).

We are an open-source project, but unfortunately, we are a team of 3 people, and I'm the only developer. So we are all over the place and can't get enough time to maintain the issues with proper docs that will help others get started with the contribution. We're now on version 3.0 of the extension, which is basically the web app in an extension form. Hopefully, following this release, we can create a roadmap and some "good first issues" for the community.

Again, thank you so much for being part of the daily.dev community. I'm closing this issue as the feature already exists but don't hesitate to reach out again.
