### ISSUE TITLE
🐛 BUG: I lost all my bookmarks

### ISSUE THREAD

**Issue by jeriiglesias** [dailydotdev/daily#317]
### What went wrong? 🤔

I lost all my bookmarks

### Expected Behavior

I should have seen all my hundreds of bookmarks

### Actual Behavior

I am seeing a blank list of bookmarks. My bookmarks list is empty.

### Steps to Reproduce Issue

app.daily.dev just kept prompting all of a sudden, with the username field blank. I filled in username but it won't save. So I logged out.
When I logged back in, using Google authentication (same as last time), all my bookmarks disappeared.

### Solution

Can you restore all my bookmarks?

#### Browser

Chrome. Fedora 34.

**Comment by idoshamun** [comment]
Hey,

It takes you to registration page because your profile is incomplete
(username is missing). It is not saved probably because you have multiple
accounts with the same email. We are slowly updating our authentication
system to get rid of legacy edge cases. Sorry for the inconvenience. Let me
know your email so I can check if you have multiple accounts assigned to
whom one of them has the bookmarks.
Send it to support at daily.dev
