### ISSUE TITLE
🐛 BUG: "Set up your profile" page cannot permit to complete profile

### ISSUE THREAD

**Issue by russoalberto** [dailydotdev/daily#318]
### What went wrong? 🤔

I cannot complete my profile because "This email is already used"
![2021-08-19_10-20](https://user-images.githubusercontent.com/296379/130034033-c441f27e-65a0-458a-919f-29f0a9be8568.png)

### Steps to Reproduce Issue

1) I login to daily.dev with my gmail Account.
2) App show the page "Set up your profile"
3) I cannot complete my profile because "This email is already used"

#### Operating System

Manjaro Linux

#### Browser
Mozilla Firefox 91.0.1 for

**Comment by idoshamun** [comment]
Hey @russoalberto,

That's because you have another account registered with the same email (probably a GitHub-based account).
Previously, we allowed such duplication to happen but now we fixed it.
Sorry for the inconvenience but if possible please send us an email to support at daily.dev and we will delete the second account.
