### ISSUE TITLE
🧩 FEATURE REQUEST: suggest new tags functionality

### ISSUE THREAD

**Issue by ariaieboy** [dailydotdev/daily#325]
### Description

I would like to have a `Suggest new tag` button like what we have in the source section so we can suggest new tags for daily.
for example right now i can suggest to add nuxtjs or laravel-livewire or livewire as new tags.

### Solution

it can be just like what we have in the source area a simple form so we can submit new tags that we want them in the daily app.
its can contain some more fields like some example article about that tag or some keywords and etc

### Alternate Solutions

I dont know that its possible or not but it can be implemented as a personal tag feature that each user define some keyword filters or any other kind of filters as a personal tag for example i love to work with TALL stack thats stand for (Tailwindcss + Alpinejs + laravel + livewire) 
then i can add a tag called #TALL-stack for example and saying that show the post with keywords of laravel livewire tailwindcss alpinejs in this tag or i can add the existing tags about this frameworks to this tag.

**Comment by idoshamun** [comment]
Let me explain in a nutshell how our tagging system works. We use an NLP algorithm to extract the keywords from the content, we then match it to our manually selected list of tags, and only then associate the tags with the article.
To create a new tag we need new sources that will provide content for this tag. Otherwise, you might see the tag on the list but there will be no content there which is not a good situation. But we do want to let the community help us manage the tags in one way or another.
