### ISSUE TITLE
QUESTION: How I can filter sources ? 

### ISSUE THREAD

**Issue by DanTsk** [dailydotdev/daily#347]
Hello!
On the `daily.dev` landing I can see functionality to filter sources and tags (screenshot below).
![image](https://user-images.githubusercontent.com/18099022/141480737-34555989-1124-4cb4-8cbe-d614c9bfacb4.png)

I've used this functionality a long time ago, but now I can't find it. Was it removed, or this UI is hidden somewhere?
Thanks.

**Comment by nimrodkra** [comment]
Hi @DanTsk, 

Thanks for reaching out! Indeed, we recently introduced a [new way to filter your feed](https://changelog.daily.dev/revamped-feed-filtering-options-212974) on daily.dev. 

The new filtering experience is focused mostly on topics (tags). Since we aim to bring the most relevant content, regardless of where it was published, we decided to focus our filtering options on tags. We hope this would simplify the filtering experience for our community. 

One of the problems we had in the previous version is that the sources lists have grown too big (+400). Most of our community weren't able to manage this list in a way that would result in a better feed. To simplify things, we introduced a new section called `Advanced` where you can filter out entire categories of content that don't match your reading preferences. 

Having said that, we do acknowledge that the option to filter sources isn't directly supported anymore. So I listed down a bunch of alternative solutions:

If you want to read content from a specific source, you have the following options:
1. Clicking on the source's icon (on the post's card) will lead you to a feed of that specific source. If you're using the web app you can save the link in your browser's bookmarks to easily access it later.
2. If you can't find content from the source you're looking for, try to search it and then go back to option 1 above
3. Use an external RSS reader to curate only the sources you like

If you want to filter out a specific source, you can do it from the new `more options` context menu that appears on every card. Once you see an article from a source you wish to block, click `more options` (⋮) and then choose "Don't show articles from {source_name}". Find out more about [how to apply filters directly from your feed](https://changelog.daily.dev/apply-filters-directly-from-cards-212973). 

To access the filtering section, click on the `settings` icon to open the left sidebar. Once opened, try clicking on either `Manage tags` and/or `Advanced`. 

![Screenshot of the sidebar](https://cloud.headwayapp.co/changelogs_images/images/big/000/078/067-177615049e95155d8cc21eee7c198e2d6e514706.png)

_p.s. we should definitely update our website accordingly ASAP_
