### ISSUE TITLE
🐛 BUG: 1gb of cache

### ISSUE THREAD

**Issue by notiv-nt** [dailydotdev/daily#372]
### What went wrong? 🤔

Can you please stop caching everything ?

![image](https://user-images.githubusercontent.com/10743009/144741861-dfa46d1a-5fa2-43c5-819b-93a9396037f5.png)

### Expected Behavior

😀

### Actual Behavior

😡

### Environment

Chrome 96

**Comment by idoshamun** [comment]
Hi @notiv-nt,

I must say that I loved your expected and actual behavior description 😂 
As for your issue, this is happening due to the default workbox configuration.
I looked into it and the root cause is media caching. Its default limit is too high.
We will fine-tune the configuration and let you know.
Thanks for pointing out this critical issue.

**Comment by ShaikRehan123** [comment]
But i am getting only 352kb 
![image](https://user-images.githubusercontent.com/83860384/147827429-b0f2f147-c2f7-48f1-8ce0-6aca0b16dc4b.png)

**Comment by idoshamun** [comment]
Thanks for validating @ShaikRehan123.
This problem seems to happen only in the web app due to service worker configuration

**Comment by idoshamun** [comment]
@notiv-nt it should be fine now. We set some limits to our workbox config.
If you want to be sure, delete the existing cache and the new cache should be capped at ~300mb.
