### ISSUE TITLE
🧩 FEATURE REQUEST: Ability to perform partial search during tagging 

### ISSUE THREAD

**Issue by sirius93** [dailydotdev/daily#650]
### Description
While performing "@" tagging in comments, would help to search by last name or just by partial text. 
i.e. For searching Nandan kumar if I type: "@Nandan" it gives me a result but does not give the same result when I type "@kumar".

### Solution
A possible solution would be to filter the result based on partial text from the DB.

**Comment by sshanzel** [comment]
Hi @sirius93, thank you for reaching out! An explanation of how our "@" tagging works:

When you initiate the mention, it will first look at the active people on the post (including if there is an author). If there are only a few of them, it will fetch your recently mentioned users.

Then once you start typing, that is when the results you have mentioned show up. You can search by username or full name (by omitting spaces). The reason you are seeing a different result on the query `@Kumar` is, that there are users who are having names/usernames starting with it.

Filtering the result with partial text would result in almost the same output since as I have mentioned, there are users that fit the query just right.
