### ISSUE TITLE
🐛 BUG: Usernames can be re-used with different capitalization

### ISSUE THREAD

**Issue by flame-0** [dailydotdev/daily#832]
Users are able to register multiple accounts with the same username, but different capitalization (e.g., "flame" and "flAme"). This can lead to confusion and security issues. The website should enforce case sensitivity for usernames.
![image](https://user-images.githubusercontent.com/40175769/223761603-4e0fe8d2-f15d-4e31-b3b4-a86a9b02feb1.png)

**Comment by idoshamun** [comment]
Hi @flame-0,

Thanks for the report! We're aware of the problem and we'll fix it :)

**Comment by NeevJewalkar** [comment]
Can I work on this problem?

**Comment by idoshamun** [comment]
Hi @NeevJewalkar,

This is a complex issue to fix and requires ops effort as well. It's not open for public contribution, unfortunately.
Thank you so much though!

**Comment by souravjain540** [comment]
Hi @idoshamun, just adding here, I think this will be fixed with this issue as well.

the same username just different capitalization gives an error while it should redirect us to the same user like every other social media platform.

![Screenshot 2023-07-27 at 2 35 23 PM](https://github.com/dailydotdev/daily/assets/53312820/eee07632-524c-4fe8-bfeb-41bef341c6d4)

![Screenshot 2023-07-27 at 2 35 08 PM](https://github.com/dailydotdev/daily/assets/53312820/a3e800a1-41c5-470a-b60b-c739a6a27c0e)

**Comment by rebelchris** [comment]
Also note this ticket, usernames should not be able to contain special characters or dots.
https://github.com/dailydotdev/daily/issues/880

**Comment by rebelchris** [comment]
Closed as completed by @idoshamun
