### ISSUE TITLE
🐛 BUG: Cannot Scroll While Writing long Comments

### ISSUE THREAD

**Issue by Anmol-Baranwal** [dailydotdev/daily#862]
## 🐛 Bug Report

I cannot scroll while writing comments in any post, which prevents me from writing detailed comments. This is a significant issue that needs to be fixed.

### What went wrong? 🤔

![Screenshot (3217)](https://user-images.githubusercontent.com/74038190/229580655-529db5bc-977e-416d-a2d1-c23836f36847.png)

Please refer to the attached screenshot, which shows that even in full-screen mode, the post button is not visible when I write a long comment.

#### Operating System

Windows 10

#### Browser

Chrome

**Comment by idoshamun** [comment]
Hi @Anmol-Baranwal,

I agree that needs to be fixed. Thanks for reporting.

**Comment by NiazMorshed2007** [comment]
Hey @idoshamun . Can you assign me this issue?

**Comment by jayant-01** [comment]
Hey @idoshamun , can I also work on this issue ?

**Comment by sshanzel** [comment]
Hello everyone, we have decided to fix this internally due to the intensity of users that are being affected. Though we appreciate the intent of fixing the issue on your own. Thank you for the offers!

This got fixed by updating our modal guidelines from here: https://github.com/dailydotdev/apps/commit/c783ecc8fe526a043ec5aa75784a6fbb3cb826c3
